config/routes.rb
Source::Application.routes.draw do
  
  resources :call_detail_records

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  match 'admin' => 'sites#index'
  match 'company' => 'sites#settings'
  match 'calls_fast_import' => 'temp_calls#fast_import'
  match 'calls_delete_new_records' => 'temp_calls#delete_new_records'
  match 'calls_download_not_added_number_list_csv' => 'temp_calls#download_not_added_number_list_csv'
  match 'calls_delete_stranded_good_records' => 'temp_calls#delete_stranded_good_records'
  match 'calls_download_not_added_call_type_list_csv' => 'temp_calls#download_not_added_call_type_list_csv'
  match 'calls_delete_stranded_bad_records1' => 'temp_calls#delete_stranded_bad_records1'
  match 'calls_download_not_added_cc_call_type_list_csv' => 'temp_calls#download_not_added_cc_call_type_list_csv'
  match 'calls_delete_stranded_bad_records2' => 'temp_calls#delete_stranded_bad_records2'
  match 'calls_delete_stranded_bad_records' => 'temp_calls#delete_stranded_bad_records'
  match "/delayed_job" => DelayedJobWeb, :anchor => false
  
  resources :user_sessions
  resources :users
  resources :call_type_infos
  resources :rating_plans
  resources :minimum_charge_ratings
  resources :local_plans
  resources :temp_calls
  resources :providers
  resources :international_rates
  resources :adjustments
  resources :other_services
  resources :lines
  resources :taxes
  resources :sales_reps
  
  resources :sites do
    member do
      post 'delete_logo1'
      post 'delete_logo2'
      post 'bill_preview'
      get 'code_image'
      get 'code_image2'
    end
  end
  
  resources :international_plans do
    member do
      post 'import'
    end
  end
  
  resources :accounts do
    resources :lines
    resources :other_services
    resources :adjustments
  end
  
  resources :billing_sessions do
    resources :bills
    member do
      get 'batch_email'
    end
  end
  
  resources :bills do
    resources :billed_taxes
    resources :billed_adjustments
    resources :billed_lines
    resources :billed_calls
    resources :billed_services
    member do
      post 'email_invoice'
    end
  end
  

  root:to => redirect('/accounts')

end

app/models/billing_session.rb
class BillingSession < ActiveRecord::Base
  acts_as_tenant(:site)
  mount_uploader :csv, FileUploader
  attr_accessible :name, :billing_date, :due_date, :start_number, :pending_flag
  belongs_to :site
  has_many :temp_calls
  has_many :bills, :dependent => :destroy
  has_and_belongs_to_many :call_detail_records
  before_create :no_pending_sessions
  # before_create :has_temp_calls
  validates_presence_of :name
  validates_uniqueness_to_tenant :name
  validates_presence_of :billing_date
  validates_presence_of :due_date
  validates_presence_of :call_detail_records, :on => :create
  validates_presence_of :start_number

  EMAILS_NOT_SENT = 0
  EMAILS_IN_PROGRESS = 1
  EMAILS_SENT = 2

  def no_pending_sessions
    return if BillingSession.count(:conditions => ['pending_flag = true']) == 0
    errors[:base] << "Cannot start a billing session. Another session is in progress."
    false
  end

  # def has_temp_calls
  #   return if TempCall.count(:conditions => ['rated = false']) > 0
  #   errors[:base] << "Cannot start a billing session. Call usage import process is not completed or hasn't started at all."
  #   false
  # end

  def batch_email_process(billing_session_id)
    Rails.logger.info "BATCH_EMAIL: Executing batch email"
    billing_session = BillingSession.find(billing_session_id)
    ActsAsTenant.with_tenant(billing_session.site) do
      begin
        #Email every bill within the billing session
        billing_session.bills.each do |bill|
          if not bill.account.billing_email.nil? and not billing_session.site.from_email.nil?
            if bill.account.billing_email.length > 0  and billing_session.site.from_email.length > 0
              # if not bill.pdf.read.length > Source::Application.config.email_attachment_max_size
                BillMailer.invoice_email(bill.account.billing_email, bill, billing_session.site).deliver
                bill.emailed = true
                bill.save
                bill = nil
              # end
            end
          end
        end
      rescue => e
        Rails.logger.error "ERROR: problem while executing batch_emailing rake task: " + e.message
        Rails.logger.error e.backtrace.join("\n")
      end
      Rails.logger.info "BATCH_EMAIL: Setting batch email to completed"
      billing_session.batch_email_status = BillingSession::EMAILS_SENT
      billing_session.save
    end
  end
  handle_asynchronously :batch_email_process, :queue => 'emailing'

  def do_billing(billing_session_id)
      self.class.connection.clear_query_cache
      Rails.logger.info "BILLING_LOG: cleared the cache so this worker can load the latest data"
      billing_session = BillingSession.find(billing_session_id)
      ActsAsTenant.with_tenant(billing_session.site) do
        begin
          Rails.logger.info "BILLING_LOG: starting billing process for: " +  ActsAsTenant.current_tenant.name.to_s + "(" + ActsAsTenant.current_tenant.id.to_s + ")"
          Rails.logger.info "BILLING_LOG: setting billing session processing flag"
          billing_session.processing_flag = true
          billing_session.status = "Reading CDRs"
          billing_session.save
          #=================
          #Archive old bills
          #=================
          # TODO: Re-build archiving process here
          # if billing_session.id >= 3 #we keep the last 2 billing sessions (not including the is being created)
          #   session_id = billing_session.id - 2
          #   billing_session.connection.execute("update bills set pdf = null, csv = null where billing_session_id < " + session_id.to_s + " and pending_flag = 0")
          #   session_id = nil
          # end
          #=============================
          #First, do the LD calls rating
          #=============================
          billing_session.call_detail_records.each do |cdr_file|
            Rails.logger.info "BILLING_LOG: Retrieving CDR for provider: " + cdr_file.provider.name.to_s
            cdr_file.provider.import_cdr(open(cdr_file.cdr.url))
          end
          cdr_file = nil
          Rails.logger.info "BILLING_LOG: performing call rating"
          billing_session.status = "Rating calls"
          billing_session.save
          do_rating
          #==================
          #Now do the Billing
          #==================
          billing_session.status = "Creating billing records"
          billing_session.save
          Rails.logger.info "BILLING_LOG: doing the billing"
          #Get the active accounts
          Rails.logger.info "BILLING_LOG: gettting active accounts"
          accounts = Account.find(:all, :select => 'id', :conditions => ['active = true'], :include => :taxes, :order => :title)
          #Generate a bill for each active account
          Rails.logger.info "BILLING_LOG: generate a bill for each active client"
          accounts.each do |account|
            Rails.logger.info "BILLING_LOG: working on client id: " + account.id.to_s + " from company: " + ActsAsTenant.current_tenant.name.to_s
            bill = Bill.new
            #Get the bill number
            Rails.logger.info "BILLING_LOG: getting bill number"
            number = Bill.maximum(:number, :conditions => 'billing_session_id = ' + billing_session.id.to_s)
            if number.nil?
              bill.number = billing_session.start_number
            else
              bill.number = number + 1
            end
            #Get the rest of the stuff (account_id, billing_session_id)
            Rails.logger.info "BILLING_LOG: getting the rest of the stuff (account_id, billing_session_id)"
            bill.account_id = account.id
            bill.billing_session_id = billing_session.id
            Rails.logger.info "BILLING_LOG: saving the bill"
            #Save the bill
            if bill.save
              Rails.logger.info "BILLING_LOG: bill saved"
              #========================================
              #Move billed charges to the billed tables
              #========================================
              billing_session.status = "Moving billing data"
              billing_session.save
              Rails.logger.info "BILLING_LOG: moving billed charges to the billed tables"
              #1.-Calls
              Rails.logger.info "BILLING_LOG: moving billed calls"
              move_billed_calls(bill.id, account.id)
              #2.-Lines
              Rails.logger.info "BILLING_LOG: moving billed lines"
              billing_session.connection.execute("insert into billed_lines(`number`, `type_of_line`, `use`, `group`, `sequence`, `amount_charged`, `bill_id`, `created_at`, `updated_at`, `site_id`) select `number`, `type_of_line`, `use`, `group`, `sequence`, `line_rate`, " + bill.id.to_s + ", current_timestamp(), current_timestamp(), `site_id` from `lines` where `account_id` = " + account.id.to_s + " and `active` = true and `port_date` <= '" + billing_session.billing_date.to_s + "'" + " and `site_id` = " + ActsAsTenant.current_tenant.id.to_s)
              #3.-Services
              Rails.logger.info "BILLING_LOG: moving billed services"
              billing_session.connection.execute("insert into billed_services(`type_of_service`, `use`, `amount_charged`, `bill_id`, `created_at`, `updated_at`, `site_id`) select `type_of_service`, `use`, `rate`, " + bill.id.to_s + ", current_timestamp(), current_timestamp(), `site_id` from other_services where `account_id` = " + account.id.to_s + " and `port_date` <= '" + billing_session.billing_date.to_s + "'" + " and `site_id` = " + ActsAsTenant.current_tenant.id.to_s)
              #4.-Adjustments
              Rails.logger.info "BILLING_LOG: moving billed adjustments"
              billing_session.connection.execute("insert into billed_adjustments(`description`, `amount_charged`, `bill_id`, `created_at`, `updated_at`, `site_id`) select `description`, `amount`, " + bill.id.to_s + ", current_timestamp(), current_timestamp(), `site_id` from adjustments where `account_id` = " + account.id.to_s + " and `apply_on` = '" + billing_session.billing_date.to_s + "'" + " and `site_id` = " + ActsAsTenant.current_tenant.id.to_s)
              #5.-Taxes
              Rails.logger.info "BILLING_LOG: moving billed taxes"
              total_charges = BilledCall.sum(:amount_charged, :conditions => "bill_id = " + bill.id.to_s) + BilledLine.sum(:amount_charged, :conditions => "bill_id = " + bill.id.to_s) + BilledService.sum(:amount_charged, :conditions => "bill_id = " + bill.id.to_s) + BilledAdjustment.sum(:amount_charged, :conditions => "bill_id = " + bill.id.to_s)
              account.taxes.each do |tax|
                Rails.logger.info "BILLING_LOG: saving total " + tax.name.to_s + " tax charges"
                billed_tax = BilledTax.new
                billed_tax.name = tax.name
                billed_tax.rate = tax.rate
                billed_tax.amount_charged = ("%.#{ActsAsTenant.current_tenant.decimals}f" % billed_tax.calculate_amount(total_charges))
                billed_tax.bill_id = bill.id
                billed_tax.save
                billed_tax = nil
              end
              total_charges = nil
              tax = nil
            end
             #Do some clean up
             Rails.logger.info "BILLING_LOG: cleaning up memory"
             bill = nil
             account = nil
             number = nil
          end
          Rails.logger.info "BILLING_LOG: deleting billed temp_calls"
          TempCall.delete_all("stranded = false")
          #Now generate the pdfs and csvs
          billing_session.status = "Generating reports"
          billing_session.save
          Rails.logger.info "BILLING_LOG: generating PDFs and CSVs"
          generate_files(billing_session)
           # generate summary report
          billing_session.status = "Generating summary"
          billing_session.save
          billing_session = BillingSession.find(billing_session.id) #Need to reload Billing Session, otherwise Carrierwave gem will fail!

app/views/billing_sessions/edit.html.erb
<%= page_title('Editing Billing Session', 'Cancel', billing_sessions_path) %>

<%= form_for(@billing_session) do |f| %><br />
  <%= error_messages(@billing_session) %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

app/views/billing_sessions/index.html.erb
<script language="javascript" type="text/javascript">setTimeout("location.reload();",10000);</script>
<%= page_title('Billing Sessions', 'Start a new billing session', new_billing_session_path) %>
<table>
	<%= table_header(@billing_sessions, [ 'Name', 'Billing date', 'Due date', 'Start number', 'Status' ]) %>
	<% @billing_sessions.each do |billing_session| %>
	  <tr>
	    <td><%=h billing_session.name %></td>
	    <td><%=h billing_session.billing_date %></td>
	    <td><%=h billing_session.due_date %></td>
	    <td><%=h billing_session.start_number %></td>
		<% if billing_session.failed? %>
			<td style="color:red">Failed</td>
		<% elsif billing_session.pending_flag? && (not billing_session.processing_flag?) %>
			<td style="color:orange">Queued</td>
		<% elsif billing_session.processing_flag? %>
			<td style="color:brown"><%= image_tag("wheel.gif", :border => 0)%> <%=h billing_session.status %></td>
		<% else %>
			<td style="color:green">Ready</td>
		<% end %>
		<% if (billing_session.pending_flag == false) && (billing_session.processing_flag == false) %>
		    <% if not billing_session.failed? %>
				<td><%= link_to(image_tag("page_white_magnify.png", :border => 0), url_for(billing_session) + get_params, :title => 'Details') %></td>
				<td><%= link_to(image_tag("page_white_edit.png", :border => 0), url_for(edit_billing_session_path(billing_session)) + get_params, :title => 'Edit') %></td>
				<% if (not billing_session.csv.nil?) && (billing_session.csv = '') %>
					<td>
						<%= link_to image_tag("page_white_excel.png"), billing_session.csv.url.to_s, :title => "Download Summary" -%>
<!-- 						<%= form_for :billing_session, :url=>{:controller=>"billing_sessions", :action=>"export_csv", :id => billing_session} do |f| -%>
							<%= image_submit_tag("page_white_excel.png", :title => "Download Summary") -%>
						<% end %> -->
					</td>
				<% end %>
			<% end %>
			<td><%= link_to(image_tag("cross.png", :border => 0), billing_session, :confirm => 'Are you sure that you want to permanently delete this item?', :method => :delete, :title => 'Delete') %></td>
		<% end %>
	  </tr>
	<% end %>
</table>

app/views/billing_sessions/new.html.erb
<%= page_title('New Billing Session', 'Cancel', billing_sessions_path) %>

<%= form_for(@billing_session) do |f| %><br />
  <%= error_messages(@billing_session) %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :billing_date %>
    <%= f.date_select :billing_date %>
  </p>
  <p>
    <%= f.label :due_date %>
    <%= f.date_select :due_date %>
  </p>
  <p>
    <%= f.label :call_detail_records %><br/>
    <% for call_detail_record in CallDetailRecord.find(:all) %>
      &nbsp;&nbsp;&nbsp;&nbsp;<input type = "checkbox" id= "<%=call_detail_record.id%>" name="call_detail_record_ids[]" value="<%=call_detail_record.id%>"><%=call_detail_record.name%><br/>
    <% end %>
  </p>
  <p>
    <%= f.label :start_number %>
    <%= f.text_field :start_number %>
  </p>
  <%= hidden_field_tag :pending_flag, params[:pending_flag] %>
  <p>
    <%= f.submit 'Start' %>
  </p>
<% end %>

app/views/billing_sessions/show.html.erb
<h2>Billing Session Details</h2>

<% if @billing_session.pending_flag == false %>
	<%= link_to 'Edit', edit_billing_session_path(@billing_session) + get_params, :class => "underlined" %> |
<% end %>
<%= link_to 'Back', billing_sessions_path + get_params, :class => "underlined" %>
<br /><br />

<p>
  <b>Name:</b>
  <%=h @billing_session.name %><br />

  <b>Billing date:</b>
  <%=h @billing_session.billing_date %><br />

  <b>Due date:</b>
  <%=h @billing_session.due_date %><br />

  <b>Start number:</b>
  <%=h @billing_session.start_number %><br />
</p>

<p>
  <%= link_to "View " + pluralize(@billing_session.bills.size, 'bill'), billing_session_bills_path(@billing_session) + get_params, :class => "underlined" %><br />
  <% if @email_count > 0 and not @site.from_email.nil? %>
	<% if @site.from_email.length > 0 %>
		<% if @billing_session.batch_email_status == BillingSession::EMAILS_IN_PROGRESS %>
			Email batch in progress<br />
		<% elsif @billing_session.batch_email_status == BillingSession::EMAILS_SENT %>
			<%= link_to "Re-Send all bills", {:controller=>"billing_sessions", :action=>"batch_email", :id => @billing_session }, :confirm => "Are you sure you want to send ALL bills AGAIN??", :class => "underlined" %><br />
		<% else %>
			<%= link_to "Email all bills", {:controller=>"billing_sessions", :action=>"batch_email", :id => @billing_session }, :confirm => "Are you sure you want to email all bills?", :class => "underlined" %><br />
		<% end %>
  	<% end %>
  <% end %>
</p>