config/routes.rb
Source::Application.routes.draw do
  
  resources :call_detail_records

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  match 'admin' => 'sites#index'
  match 'company' => 'sites#settings'
  match 'calls_fast_import' => 'temp_calls#fast_import'
  match 'calls_delete_new_records' => 'temp_calls#delete_new_records'
  match 'calls_download_not_added_number_list_csv' => 'temp_calls#download_not_added_number_list_csv'
  match 'calls_delete_stranded_good_records' => 'temp_calls#delete_stranded_good_records'
  match 'calls_download_not_added_call_type_list_csv' => 'temp_calls#download_not_added_call_type_list_csv'
  match 'calls_delete_stranded_bad_records1' => 'temp_calls#delete_stranded_bad_records1'
  match 'calls_download_not_added_cc_call_type_list_csv' => 'temp_calls#download_not_added_cc_call_type_list_csv'
  match 'calls_delete_stranded_bad_records2' => 'temp_calls#delete_stranded_bad_records2'
  match 'calls_delete_stranded_bad_records' => 'temp_calls#delete_stranded_bad_records'
  match "/delayed_job" => DelayedJobWeb, :anchor => false
  
  resources :user_sessions
  resources :users
  resources :call_type_infos
  resources :rating_plans
  resources :minimum_charge_ratings
  resources :local_plans
  resources :temp_calls
  resources :providers
  resources :international_rates
  resources :adjustments
  resources :other_services
  resources :lines
  resources :taxes
  resources :sales_reps
  
  resources :sites do
    member do
      post 'delete_logo1'
      post 'delete_logo2'
      post 'bill_preview'
      get 'code_image'
      get 'code_image2'
    end
  end
  
  resources :international_plans do
    member do
      post 'import'
    end
  end
  
  resources :accounts do
    resources :lines
    resources :other_services
    resources :adjustments
  end
  
  resources :billing_sessions do
    resources :bills
    member do
      get 'batch_email'
    end
  end
  
  resources :bills do
    resources :billed_taxes
    resources :billed_adjustments
    resources :billed_lines
    resources :billed_calls
    resources :billed_services
    member do
      post 'email_invoice'
    end
  end
  

  root:to => redirect('/accounts')

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  acts_as_tenant(:site)
  mount_uploader :pdf, FileUploader
  mount_uploader :csv, FileUploader
  # attr_accessible :name, :rate
  belongs_to :site
  belongs_to :billing_session
  belongs_to :account
  has_many :billed_calls, :dependent => :destroy
  has_many :billed_lines, :dependent => :destroy,:order => '`type_of_line`, `use`, `number`'
  has_many :billed_services, :dependent => :destroy
  has_many :billed_taxes, :dependent => :destroy
  has_many :billed_adjustments, :dependent => :destroy

end

def generate_bill_files(bill)
  require 'tempfile'
  require 'csv'
  Rails.logger.info "BILLING_LOG: generating bill files for bill id: " +  bill.id.to_s + " and company: " + ActsAsTenant.current_tenant.name.to_s + "(" + ActsAsTenant.current_tenant.id.to_s + ")"
  # if bill.pending_flag == false
  #   bill.pending_flag = true
  #   # bill.save
  # end
  if bill.billed_calls.count < Source::Application.config.max_amount_of_records_per_bill
    Rails.logger.info "BILLING_LOG: generating PDF for bill id: " +  bill.id.to_s + " and company: " + ActsAsTenant.current_tenant.name.to_s + "(" + ActsAsTenant.current_tenant.id.to_s + ")"
    file = StringIO.new(BillsReport.new(:margin => 0).default_invoice(bill, bill.site, false))
    file.class.class_eval { attr_accessor :original_filename, :content_type } #add attributes
    file.original_filename = (bill.account.title + bill.billing_session.name).titleize.gsub(/ /,'') + ".pdf"
    file.content_type = "application/pdf"
    bill.pdf = file
    Rails.logger.info "MEMORY_MANAGEMENT: [generate_bill_files - pdf] starting garbage collector"
    GC.start #force garbage collector
  end
  Rails.logger.info "BILLING_LOG: generating CSV for bill id: " +  bill.id.to_s + " and company: " + ActsAsTenant.current_tenant.name.to_s + "(" + ActsAsTenant.current_tenant.id.to_s + ")"
  csv_string = CSV.generate do |csv| 
    csv << ["Originating_Number","Call_Date","Call_Time","Duration_sec","Destination","Destination_Province_State","Destination_Number","Account_Code","Charge_$","Call_Type"]
    BilledCall.where("bill_id = " + bill.id.to_s).find_each do |call|
      csv << [call.orig_tn, call.date, call.time, call.duration_sec, call.destination, call.dest_prov_state, call.term_tn, call.code, call.amount_charged, call.call_type]
    end
    Rails.logger.info "MEMORY_MANAGEMENT: [generate_bill_files - csv] starting garbage collector"
    GC.start #force garbage collector
  end
  file = StringIO.new(csv_string)
  file.class.class_eval { attr_accessor :original_filename, :content_type } #add attributes
  file.original_filename = (bill.account.title + bill.billing_session.name).titleize.gsub(/ /,'') + ".csv"
  file.content_type = "application/csv"
  bill.csv = file
  bill.pending_flag = false
  bill.save!
  FileUtils.remove_dir("#{Rails.root}/public/uploads/tmp", :force => true)
  Rails.logger.info "BILLING_LOG: finished generating bill files for bill id: " +  bill.id.to_s + " and company: " + ActsAsTenant.current_tenant.name.to_s + "(" + ActsAsTenant.current_tenant.id.to_s + ")"
  file = nil
  csv_string = nil
  call = nil
  csv = nil
  uploader = nil
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  layout "application"
  
  require 'prawn'
  require 'csv'
  
  def email_invoice
    bill = Bill.find(params[:id], :include => [:account])
    BillMailer.invoice_email(bill.account.billing_email, bill, ActsAsTenant.current_tenant).deliver
    respond_to do |format|
      bill.emailed = true
      bill.save
      flash[:notice] = 'Bill was successfully emailed to: ' + bill.account.billing_email
      format.html { redirect_to(billing_session_bills_url(bill.billing_session.id)) }
    end
    bill = nil
  end
  
  # def get_invoice
  #   bill = Bill.find(params[:id])
  #   # send_data bill.pdf, :filename => (bill.account.title + bill.billing_session.name).titleize.gsub(/ /,'') + ".pdf", :type => :pdf
  #   send_data bill.pdf.read,  :filename => bill.pdf.file.filename, :type => :pdf
  #   bill = nil
  # end
  
  # def export_csv
  #   bill = Bill.find(params[:id])
  #   # send_data bill.csv, :type => "text/csv", :filename => (bill.account.title + bill.billing_session.name).titleize.gsub(/ /,'') + ".csv"
  #   send_data bill.csv.read, :type => "text/csv", :filename => bill.csv.file.filename
  #   bill = nil
  # end
  
  # GET /bills
  # GET /bills.xml
  def index
    @site = ActsAsTenant.current_tenant
    @billing_session = BillingSession.find(params[:billing_session_id], :include => [:bills, {:bills => :account}])
    @bills = Kaminari.paginate_array(@billing_session.bills).page(params[:page]).per(Source::Application.config.items_per_page)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.xml
  def show
    @billing_session = BillingSession.find(params[:billing_session_id])
    @bill = @billing_session.bills.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.xml
  def new
    @billing_session = BillingSession.find(params[:billing_session_id])
    @bill = @billing_session.bills.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @billing_session = BillingSession.find(params[:billing_session_id])
    @bill = @billing_session.bills.find(params[:id])
  end

  # POST /bills
  # POST /bills.xml
  def create
    @billing_session = BillingSession.find(params[:billing_session_id])
    @bill = @billing_session.bills.new(params[:bill])

    respond_to do |format|
      if @bill.save
        flash[:notice] = 'Bill was successfully created.'
        format.html { redirect_to(billing_session_lines_url) }
        format.xml  { render :xml => @bill, :status => :created, :location => @bill }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.xml
  def update
    @billing_session = BillingSession.find(params[:billing_session_id])
    @bill = @billing_session.bills.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        flash[:notice] = 'Bill was successfully updated.'
        format.html { redirect_to(billing_session_bills_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.xml
  def destroy
    @billing_session = BillingSession.find(params[:billing_session_id])
    @bill = @billing_session.bills.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to(billing_session_bills_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/bills/index.html.erb
<%= page_title(@billing_session.name + " bills", 'Back', billing_session_path(@billing_session)) %>

<%= pagination @bills %>
<% if @bills.length > 0 %>
<table>
  <tr>
    <th>Number</th>
    <th>Client</th>
  </tr>
<% else %>
	<table>
		No bills have been generated.
<% end %>

<% @bills.each do |bill| %>
  <tr>
    <td><%=h bill.number %></td>
    <td><%=h bill.account.title %></td>
	<% if bill.pending_flag == true %>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>Re-generating bill. Please refresh this page in a few minutes.</td>
	<% else %>
		<% if not bill.csv.blank? %>
			<% if not bill.pdf.blank? %>
				<td>
					<%= link_to image_tag("page_white_acrobat.png"), bill.pdf.url.to_s, :title => "Download PDF" -%>
<!-- 					<%= form_for :bill, :url=>{:controller=>"bills", :action=>"get_invoice", :id => bill} do |f| -%>
						<%= image_submit_tag("page_white_acrobat.png", :title => "Download PDF") -%>
					<% end %> -->
				</td>
			<% else %>
				<td></td>
			<% end %>
			<% if not bill.csv.blank? %>
				<td>
					<%= link_to image_tag("page_white_excel.png"), bill.csv.url.to_s, :title => "Download Long Distance Usage" -%>
<!-- 					<%= form_for :bill, :url=>{:controller=>"bills", :action=>"export_csv", :id => bill} do |f| -%>
						<%= image_submit_tag("page_white_excel.png", :title => "Download Long Distance Usage") -%>
					<% end %> -->
				</td>
			<% else %>
				<td></td>
			<% end %>
			<% if not bill.account.billing_email.nil? and not @site.from_email.nil? %>
				<% if bill.account.billing_email.length > 0  and @site.from_email.length > 0 %>
					<% if bill.pdf.length > Source::Application.config.email_attachment_max_size %>
						<td><%= image_tag("email_error.png", :border => 0)%></td>					
					<% else %>
						<% if bill.emailed %>
						<td>
							<%= form_for :bill, :url=>{:controller=>"bills", :action=>"email_invoice", :id => bill} do |f| -%>
								<%= image_submit_tag("email_go.png", :confirm => "Email bill to client AGAIN??" + "\nTo: " + bill.account.billing_email + "\nFrom: " + @site.from_email, :title => "Email") -%>
							<% end %>
						</td>						
						<% else %>
							<td>
								<%= form_for :bill, :url=>{:controller=>"bills", :action=>"email_invoice", :id => bill} do |f| -%>
									<%= image_submit_tag("email.png", :confirm => "Email bill to client?" + "\nTo: " + bill.account.billing_email + "\nFrom: " + @site.from_email, :title => "Email") -%>
								<% end %>
							</td>
						<% end %>
					<% end %>
				<% else %>
					<td></td>
				<% end %>
			<% else %>
				<td></td>
			<% end %>
		<%else%>
			<td><%= image_tag("lock.png", :border => 0)%></td>
			<td></td>
			<td></td>
		<% end %>
<!-- 		<td><%= link_to image_tag("page_white_edit.png", :border => 0), url_for([@billing_session, bill]) + get_params, :title => 'Edit' %></td>
	    <td><%= link_to image_tag("cross.png", :border => 0), [@billing_session, bill], :confirm => 'Are you sure?', :method => :delete, :title => 'Delete' %></td> -->
	<% end %>
  </tr>
<% end %>
</table>
<%= pagination @bills %>

app/views/bills/show.html.erb
<%= page_title('Bill details', 'Back', billing_session_bills_path) %>
<p>
  <b>Invoice Number:</b>
  <%=h @bill.number %><br />

  <b>Client:</b>
  <%=h @bill.account.title %><br />

  <b>Billing session:</b>
  <%=h @bill.billing_session.name %><br />
</p>

<p>
	<%= link_to pluralize(@bill.billed_lines.size, 'line'), bill_billed_lines_path(@bill)  + get_params, :class => "underlined" %><br />
	<%= link_to pluralize(@bill.billed_services.size, 'service'), bill_billed_services_path(@bill) + get_params, :class => "underlined" %><br />
	<%= link_to pluralize(@bill.billed_calls.size, 'call'), bill_billed_calls_path(@bill) + get_params, :class => "underlined" %><br />
	<%= link_to pluralize(@bill.billed_adjustments.size, 'adjustment'), bill_billed_adjustments_path(@bill) + get_params, :class => "underlined" %><br />
	<%= link_to pluralize(@bill.billed_taxes.size, 'tax'), bill_billed_taxes_path(@bill) + get_params, :class => "underlined" %><br />
</p>