config/routes.rb
Source::Application.routes.draw do
  
  resources :call_detail_records

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  match 'admin' => 'sites#index'
  match 'company' => 'sites#settings'
  match 'calls_fast_import' => 'temp_calls#fast_import'
  match 'calls_delete_new_records' => 'temp_calls#delete_new_records'
  match 'calls_download_not_added_number_list_csv' => 'temp_calls#download_not_added_number_list_csv'
  match 'calls_delete_stranded_good_records' => 'temp_calls#delete_stranded_good_records'
  match 'calls_download_not_added_call_type_list_csv' => 'temp_calls#download_not_added_call_type_list_csv'
  match 'calls_delete_stranded_bad_records1' => 'temp_calls#delete_stranded_bad_records1'
  match 'calls_download_not_added_cc_call_type_list_csv' => 'temp_calls#download_not_added_cc_call_type_list_csv'
  match 'calls_delete_stranded_bad_records2' => 'temp_calls#delete_stranded_bad_records2'
  match 'calls_delete_stranded_bad_records' => 'temp_calls#delete_stranded_bad_records'
  match "/delayed_job" => DelayedJobWeb, :anchor => false
  
  resources :user_sessions
  resources :users
  resources :call_type_infos
  resources :rating_plans
  resources :minimum_charge_ratings
  resources :local_plans
  resources :temp_calls
  resources :providers
  resources :international_rates
  resources :adjustments
  resources :other_services
  resources :lines
  resources :taxes
  resources :sales_reps
  
  resources :sites do
    member do
      post 'delete_logo1'
      post 'delete_logo2'
      post 'bill_preview'
      get 'code_image'
      get 'code_image2'
    end
  end
  
  resources :international_plans do
    member do
      post 'import'
    end
  end
  
  resources :accounts do
    resources :lines
    resources :other_services
    resources :adjustments
  end
  
  resources :billing_sessions do
    resources :bills
    member do
      get 'batch_email'
    end
  end
  
  resources :bills do
    resources :billed_taxes
    resources :billed_adjustments
    resources :billed_lines
    resources :billed_calls
    resources :billed_services
    member do
      post 'email_invoice'
    end
  end
  

  root:to => redirect('/accounts')

end

app/models/billed_adjustment.rb
class BilledAdjustment < ActiveRecord::Base
  acts_as_tenant(:site)
  attr_accessible :description, :amount_charged
  belongs_to :site
  belongs_to :bill
end

app/controllers/billed_adjustments_controller.rb
class BilledAdjustmentsController < ApplicationController
  layout "application"

  # GET /billed_adjustments
  # GET /billed_adjustments.xml
  def index
    @bill = Bill.find(params[:bill_id])
    #@billed_adjustments = BilledAdjustment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @billed_adjustments }
    end
  end

  # GET /billed_adjustments/new
  # GET /billed_adjustments/new.xml
  def new
    @bill = Bill.find(params[:bill_id])
    @billed_adjustment = @bill.billed_adjustments.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @billed_adjustment }
    end
  end

  # GET /billed_adjustments/1/edit
  def edit
    @bill = Bill.find(params[:bill_id])
    @billed_adjustment = @bill.billed_adjustments.find(params[:id])
  end

  # POST /billed_adjustments
  # POST /billed_adjustments.xml
  def create
    @bill = Bill.find(params[:bill_id])
    @billed_adjustment = @bill.billed_adjustments.new(params[:billed_adjustment])

    respond_to do |format|
      if @billed_adjustment.save
        @bill.billed_taxes.each do |billed_tax|
          billed_tax.recalculate
        end
        #We have to save the flag here, other wise it woun't reflect when the landing page is loaded
        @bill.pending_flag = true
        @bill.save
        call_rake :regenerate_bill, :bill_id => params[:bill_id]
        flash[:notice] = 'Bill is being re-generated.'
        format.html { redirect_to(billing_session_bills_url(@bill.billing_session) + "?page=" + params[:page].to_s) }
        format.xml  { render :xml => @billed_adjustment, :status => :created, :location => @billed_adjustment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @billed_adjustment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /billed_adjustments/1
  # PUT /billed_adjustments/1.xml
  def update
    @bill = Bill.find(params[:bill_id])
    @billed_adjustment = @bill.billed_adjustments.find(params[:id])

    respond_to do |format|
      if @billed_adjustment.update_attributes(params[:billed_adjustment])
        @bill.billed_taxes.each do |billed_tax|
          billed_tax.recalculate
        end
        #We have to save the flag here, other wise it woun't reflect when the landing page is loaded
        @bill.pending_flag = true
        @bill.save
        call_rake :regenerate_bill, :bill_id => params[:bill_id]
        flash[:notice] = 'Bill is being re-generated.'
        format.html { redirect_to(billing_session_bills_url(@bill.billing_session) + "?page=" + params[:page].to_s) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @billed_adjustment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /billed_adjustments/1
  # DELETE /billed_adjustments/1.xml
  def destroy
    @bill = Bill.find(params[:bill_id])
    @billed_adjustment = @bill.billed_adjustments.find(params[:id])
    @billed_adjustment.destroy
    
    @bill.billed_taxes.each do |billed_tax|
      billed_tax.recalculate
    end
    #We have to save the flag here, other wise it woun't reflect when the landing page is loaded
    @bill.pending_flag = true
    @bill.save
    call_rake :regenerate_bill, :bill_id => params[:bill_id]
    flash[:notice] = 'Bill is being re-generated.'

    respond_to do |format|
      format.html { redirect_to :back }
      format.xml  { head :ok }
    end
  end
end

app/views/billed_adjustments/edit.html.erb
<%= page_title('Editing Billed Adjustment', 'Cancel', bill_billed_adjustments_path) %>

<%= form_for [@bill, @billed_adjustment], :url=>{ :controller => :billed_adjustments, :action => :update, :page => params[:page] } do |f| %>
  <%= error_messages(@billed_adjustment) %>

  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :amount_charged %>
    <%= f.text_field :amount_charged %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

app/views/billed_adjustments/index.html.erb
<%= page_title_multiple_links('Adjustments Billed for ' + @bill.account.title + " (" + @bill.billing_session.name + ")", 'Add a new adjustment to the bill', new_bill_billed_adjustment_path(@bill), 'Back', billing_session_bill_path(@bill.billing_session.id, @bill)) %>
<table>
	<%= table_header(@bill.billed_adjustments, [ 'Description', 'Amount charged' ]) %>
	<% @bill.billed_adjustments.each do |billed_adjustment| %>
		<%= table_row([ billed_adjustment.description, billed_adjustment.amount_charged ], [@bill, billed_adjustment], edit_bill_billed_adjustment_path(@bill, billed_adjustment)) %>
	<% end %>
</table>

app/views/billed_adjustments/new.html.erb
<%= page_title('New Billed Adjustment', 'Cancel', bill_billed_adjustments_path) %>

<%= form_for [@bill, @billed_adjustment], :url=>{ :controller => :billed_adjustments, :action => :create, :page => params[:page] } do |f| %>
  <%= error_messages(@billed_adjustment) %>

<%= hidden_field_tag :bill_id, params[:bill_id] %>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :amount_charged %>
    <%= f.text_field :amount_charged %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>