config/routes.rb
Source::Application.routes.draw do
  
  resources :call_detail_records

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  match 'admin' => 'sites#index'
  match 'company' => 'sites#settings'
  match 'calls_fast_import' => 'temp_calls#fast_import'
  match 'calls_delete_new_records' => 'temp_calls#delete_new_records'
  match 'calls_download_not_added_number_list_csv' => 'temp_calls#download_not_added_number_list_csv'
  match 'calls_delete_stranded_good_records' => 'temp_calls#delete_stranded_good_records'
  match 'calls_download_not_added_call_type_list_csv' => 'temp_calls#download_not_added_call_type_list_csv'
  match 'calls_delete_stranded_bad_records1' => 'temp_calls#delete_stranded_bad_records1'
  match 'calls_download_not_added_cc_call_type_list_csv' => 'temp_calls#download_not_added_cc_call_type_list_csv'
  match 'calls_delete_stranded_bad_records2' => 'temp_calls#delete_stranded_bad_records2'
  match 'calls_delete_stranded_bad_records' => 'temp_calls#delete_stranded_bad_records'
  match "/delayed_job" => DelayedJobWeb, :anchor => false
  
  resources :user_sessions
  resources :users
  resources :call_type_infos
  resources :rating_plans
  resources :minimum_charge_ratings
  resources :local_plans
  resources :temp_calls
  resources :providers
  resources :international_rates
  resources :adjustments
  resources :other_services
  resources :lines
  resources :taxes
  resources :sales_reps
  
  resources :sites do
    member do
      post 'delete_logo1'
      post 'delete_logo2'
      post 'bill_preview'
      get 'code_image'
      get 'code_image2'
    end
  end
  
  resources :international_plans do
    member do
      post 'import'
    end
  end
  
  resources :accounts do
    resources :lines
    resources :other_services
    resources :adjustments
  end
  
  resources :billing_sessions do
    resources :bills
    member do
      get 'batch_email'
    end
  end
  
  resources :bills do
    resources :billed_taxes
    resources :billed_adjustments
    resources :billed_lines
    resources :billed_calls
    resources :billed_services
    member do
      post 'email_invoice'
    end
  end
  

  root:to => redirect('/accounts')

end

app/models/other_service.rb
class OtherService < ActiveRecord::Base
  acts_as_tenant(:site)
  attr_accessible :type_of_service, :use, :rate, :port_date
  belongs_to :site
  belongs_to :account
  validates_presence_of :type_of_service
  validates_presence_of :rate
  validates_numericality_of :rate
end

app/controllers/other_services_controller.rb
class OtherServicesController < ApplicationController
  layout "application"

  def index
    @account = Account.find(params[:account_id])
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @other_services }
    end
  end

  def new
    @account = Account.find(params[:account_id])
    @other_service = @account.other_services.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @other_service }
    end
  end

  def edit
    @account = Account.find(params[:account_id])
    @other_service = @account.other_services.find(params[:id])
  end

  def create
    @account = Account.find(params[:account_id])
    @other_service = @account.other_services.new(params[:other_service])

    respond_to do |format|
      if @other_service.save
        flash[:notice] = 'Service was successfully created.'
        format.html { redirect_to account_other_services_url(:page => params[:page], :search_string => params[:search_string]) }
        format.xml  { render :xml => @other_service, :status => :created, :location => @other_service }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @other_service.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    @account = Account.find(params[:account_id])
    @other_service = @account.other_services.find(params[:id])

    respond_to do |format|
      if @other_service.update_attributes(params[:other_service])
        flash[:notice] = 'Service was successfully updated.'
        format.html { redirect_to account_other_services_url(:page => params[:page], :search_string => params[:search_string]) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @other_service.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @account = Account.find(params[:account_id])
    @other_service = @account.other_services.find(params[:id])
    @other_service.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.xml  { head :ok }
    end
  end
end

app/views/other_services/edit.html.erb
<%= page_title('Editing Service for ' + @account.title, 'Cancel', account_other_services_path) %>

<%= form_for [@account,@other_service], :url=>{ :controller => :other_services, :action => :update, :page => params[:page], :search_string => params[:search_string] } do |f| %>
  <%= error_messages(@other_service) %>

  <p>
    <%= f.label :type_of_service, 'Type' %>
    <%= f.text_field :type_of_service %>
  </p>
  <p>
    <%= f.label :use %>
    <%= f.text_field :use %>
  </p>
  <p>
    <%= f.label :rate %>
    <%= f.text_field :rate %>
  </p>
  <p>
    <%= f.label :port_date %>
    <%= f.date_select :port_date %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

app/views/other_services/index.html.erb
<%= page_title_multiple_links('Services for ' + @account.title, 'Add new service', new_account_other_service_path(@account), 'Back', account_path(@account)) %>
<table>
	<%= table_header(@account.other_services, [ 'Type', 'Use', 'Rate', 'Port date' ]) %>
	<% @account.other_services.each do |service| %>
		<%= table_row([ service.type_of_service, service.use, service.rate, service.port_date ], [@account,service], edit_account_other_service_path(@account,service)) %>
	<% end %>
</table>

app/views/other_services/new.html.erb
<%= page_title('New Service for ' + @account.title, 'Cancel', account_other_services_path) %>

<%= form_for [@account,@other_service], :url=>{ :controller => :other_services, :action => :create, :page => params[:page], :search_string => params[:search_string] } do |f| %>
  <%= error_messages(@other_service) %>

<%= hidden_field_tag :account_id, params[:account_id] %>
  <p>
    <%= f.label :type_of_service, 'Type' %>
    <%= f.text_field :type_of_service %>
  </p>
  <p>
    <%= f.label :use %>
    <%= f.text_field :use %>
  </p>
  <p>
    <%= f.label :rate %>
    <%= f.text_field :rate %>
  </p>
  <p>
    <%= f.label :port_date %>
    <%= f.date_select :port_date %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>